### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by SachaTending** [KotMilkMeoWtwo/MeowLandPlugin#18]
[05-17-2023 14:43:20] [E] java.lang.RuntimeException: Error loading mod MeowLand plugin
        at mindustry.mod.Mods.contextRun(Mods.java:800)
        at mindustry.mod.Mods.lambda$eachClass$30(Mods.java:788)
        at arc.struct.Seq.each(Seq.java:182)
        at mindustry.mod.Mods.eachClass(Mods.java:788)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:77)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read()" because "in" is null
        at ru.meowland.utils.ResourceUtil.copy(ResourceUtil.java:18)
        at ru.meowland.config.Bundle.generate(Bundle.java:57)
        at ru.meowland.config.Bundle.init(Bundle.java:37)
        at ru.meowland.MeowlandPlugin.init(MeowlandPlugin.java:34)
        at mindustry.mod.Mods.lambda$eachClass$29(Mods.java:788)
        at mindustry.mod.Mods.contextRun(Mods.java:798)
        ... 6 more

**Comment by KotMilkMeoWtwo** [comment]
config/mods/MeowLand/config.yml is exists?

**Comment by SachaTending** [comment]
yes

**Comment by SachaTending** [comment]
im installed plugin сейчас

**Comment by KotMilkMeoWtwo** [comment]
Can u send config.yml?

**Comment by SachaTending** [comment]
nvm plugin works

**Comment by Pelmenik123** [comment]
топ 10 решения проблемы
